// Generated by CoffeeScript 1.7.1
(function() {
  var Meals2Text, colors, document, sprintf;

  require('sugar');

  sprintf = require("sprintf-js").sprintf;

  colors = require('colors');

  module.exports = Meals2Text = (function() {
    function Meals2Text() {}

    Meals2Text.prototype.toConsole = function(meals) {
      var out;
      out = this.createDoc(meals, null, true);
      return console.log(out.text);
    };

    Meals2Text.prototype.toJSON = function(meals) {
      return JSON.stringify(meals);
    };

    Meals2Text.prototype.toTxt = function(meals, title) {
      var out;
      out = this.createDoc(meals, title);
      return out.text;
    };

    Meals2Text.prototype.createDoc = function(meals, title, colours) {
      debugger;
      var calories, day, doc, meal, mealGroups, _i, _len;
      mealGroups = meals != null ? meals.groupBy(function(meal) {
        return meal.date.format('{Weekday} {Month} {dd}, {yyyy}');
      }) : void 0;
      doc = new document;
      if (title) {
        this.writeHeading(doc, meals, title);
      }
      for (day in mealGroups) {
        meals = mealGroups[day];
        doc.addText(day);
        calories = 0;
        for (_i = 0, _len = meals.length; _i < _len; _i++) {
          meal = meals[_i];
          doc.addLine(this.meal2Text(meal, colours));
          calories += meal.calories;
        }
        this.writeTotalCalories(doc, calories, colours);
        doc.addNewLine();
      }
      return doc;
    };

    Meals2Text.prototype.writeHeading = function(doc, meals, title) {
      var dateFinish, dateStart;
      dateStart = meals.first().date.format('{Weekday} {Month} {dd}, {yyyy}');
      dateFinish = meals[meals.length - 1].date.format('{Weekday} {Month} {dd}, {yyyy}');
      doc.addText(title);
      doc.addText(" -- ");
      doc.addText(dateStart + " - " + dateFinish);
      doc.addSection();
      doc.addNewLine();
      return doc.addNewLine();
    };

    Meals2Text.prototype.writeTotalCalories = function(doc, calories, colours) {
      var cals, sep;
      sep = sprintf('%61s', "---------");
      cals = sprintf('%56s cals', calories);
      if (colours) {
        sep = sep.grey;
        cals = cals.green;
      }
      doc.addLine(sep);
      return doc.addLine(cals);
    };

    Meals2Text.prototype.meal2Text = function(meal, colours) {
      var foodcals, mealStr, time;
      if (meal._id) {
        mealStr = sprintf('%2s| ', meal._id);
        if (colours) {
          mealStr = mealStr.grey;
        }
      } else {
        mealStr = sprintf('   ') + " ";
      }
      time = meal.date.format('{hh}:{mm}{tt}');
      foodcals = sprintf('%6s | %-35s | %4s cals', time, meal.foods, meal.calories);
      if (meal.important) {
        foodcals += " *";
        if (colours) {
          foodcals = foodcals.yellow;
        }
      }
      mealStr += foodcals;
      return mealStr;
    };

    return Meals2Text;

  })();

  document = (function() {
    function document() {
      this.text = '';
    }

    document.prototype.addText = function(text) {
      this.text = this.text.concat(text);
      return this;
    };

    document.prototype.addNewLine = function() {
      this.text = this.text.concat('\n');
      return this;
    };

    document.prototype.addLine = function(text) {
      this.text = this.text.concat('\n', text);
      return this;
    };

    document.prototype.addSection = function() {
      this.addLine('------------------------------------');
      return this;
    };

    return document;

  })();

}).call(this);
